### ISSUE TITLE
copr is empty for Fedora 29

### ISSUE THREAD

**Issue by iliis** [vddvss/linux-gpib-packaging#1]
I tried to install linux-gpib on Fedora 29, but dnf did not find any packages. Looking at https://copr-be.cloud.fedoraproject.org/results/vddvss/linux-gpib/fedora-29-x86_64/repodata/1cb61ea996355add02b1426ed4c1780ea75ce0c04c5d1107c025c3fbd7d8bcae-primary.xml.gz shows zero packages.

Using the Fedora rawhide or 28 repo seems to work. Unfortunately, I cannot install the python bindings:

```
$ sudo dnf install python3-linux-gpib                
Copr repo for linux-gpib owned by vddvss                                                                                                                      2.0 kB/s | 9.4 kB     00:04    
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.6 needed by python3-linux-gpib-4.1.0-1.20180529svn1753.fc29.x86_64
```

**Comment by vddvss** [comment]
Sorry about that, I tend to skip every other Fedora release, and am still on F28, so didn't notice this. I had the copr set up for automated copr forking for new version, which seems like it didn't work (`mock` did FWIW). I've pushed a new build for F29, and the packages are there now. Firing it up in a VM, it looks like python package installs. 

Let me know if it works on your end, and I can close this bug. 

As an aside, I'm due to pull in a new version of linux-gpib, which I hope to get up in the next week or so, and I've got to figure out the best way to automate some of the testing...

**Comment by iliis** [comment]
Cool, thanks for the quick response! I'll try it out on monday, when I'm back at work ;)

**Comment by iliis** [comment]
Hm, so the installation works fine. But I get the following when I try to use the python package:

```
Python 3.7.2 (default, Jan 16 2019, 19:49:22) 
[GCC 8.2.1 20181215 (Red Hat 8.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gpib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib64/python3.7/site-packages/gpib.cpython-37m-x86_64-linux-gnu.so: symbol ibspb version GPIB_DUMMY_VERSION not defined in file libgpib.so.0 with link time reference
```
Might be something left over from my manual installation from source though.

**Comment by iliis** [comment]
Hm, there doesn't seem to be any function called `ibsp` at all in the source, altough there is an `ibspb`:
```
$ readelf -Ws libgpib.so.0 | grep ibsp
    88: 00000000000065f0   125 FUNC    GLOBAL DEFAULT   13 ibspb@@GPIB_DUMMY_VERSION
```

**Comment by vddvss** [comment]
Ok, that is weird. Using a fresh install of F29 on a VM with a NI-GPIB-USB-HS adapter passed through, I am able to install and connect to an instrument using the Python interface. If you installed it using the source package, I imagine there could be some files still around from that, which could be causing the issue, especially if it is a different version of the library. 

I would uninstall all of the linux-gpib packages from the copr (`sudo dnf remove "*linux-gpib*"`), and then clean up any remaining files from the source install (I think you should be able to do `make uninstall` from the source directory, and you can check with `find /usr -iname "*gpib*" 2> /dev/null`). Probably wouldn't hurt to reboot afterwards. After that, you should be able to reinstall from the copr.

**Comment by iliis** [comment]
Looks like I missed something! I tried again to remove everything from the source package, this time a bit more thoroughly, and it works now :)
Thanks for your help!
